import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { expand } from './config.js';
import { which } from './cli-adapter.js';

/**
 * cloudflared integration.
 *
 * Two modes, and the difference matters more than it looks:
 *
 *  quick tunnel  `cloudflared tunnel --url http://127.0.0.1:8787`
 *                free, zero setup, and the hostname is random and dies with the
 *                process. Every client you pointed at it (Warp, a phone app, a
 *                colleague's script) goes dead on the next restart. We use it for
 *                trials and say so out loud.
 *
 *  named tunnel  `cloudflared tunnel create` + `tunnel route dns` once, then
 *                `tunnel run` forever. Stable hostname, survives restarts, and the
 *                ingress file is plain YAML you can keep in a repo. This is what
 *                `keysmith tunnel setup` gives you.
 *
 * Either way the gateway itself still requires an API key: the tunnel is transport,
 * not authentication.
 */

export function cloudflaredBin() {
  return which('cloudflared');
}

export function certPath() {
  return expand('~/.cloudflared/cert.pem');
}

export function hasCloudflareCert() {
  return fs.existsSync(certPath());
}

export function tunnelConfigPath() {
  return expand('~/.cloudflared/keysmith.yml');
}

export async function listNamedTunnels() {
  const bin = cloudflaredBin();
  if (!bin) return { error: 'cloudflared is not installed (brew install cloudflared)' };
  if (!hasCloudflareCert()) return { error: `no Cloudflare origin certificate at ${certPath()} — run \`cloudflared tunnel login\`` };
  try {
    const out = await run(bin, ['tunnel', 'list', '--name', 'keysmith'], { timeout: 20_000 });
    const rows = out
      .split('\n')
      .slice(1)
      .map((l) => l.trim())
      .filter(Boolean)
      .map((l) => {
        const [id, name, created, conn] = l.split(/\s{2,}/);
        return { id, name, created, connections: conn };
      });
    return { tunnels: rows };
  } catch (e) {
    return { error: e.message };
  }
}

/** Write the ingress file for a named tunnel and remember it in keysmith's config. */
export function writeTunnelConfig({ tunnelName, tunnelId, hostname, port, credentialsFile }) {
  const p = tunnelConfigPath();
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const body = `# generated by \`keysmith tunnel setup\` — keysmith rewrites this file, edit with that in mind
tunnel: ${tunnelId || tunnelName}
credentials-file: ${credentialsFile || expand(`~/.cloudflared/${tunnelId}.json`)}

ingress:
  - hostname: ${hostname}
    service: http://127.0.0.1:${port}
  - service: http_status:404
`;
  fs.writeFileSync(p, body);
  return p;
}

export function readTunnelConfig() {
  const p = tunnelConfigPath();
  if (!fs.existsSync(p)) return null;
  const text = fs.readFileSync(p, 'utf8');
  const get = (k) => (text.match(new RegExp(`^${k}:\\s*(.+)$`, 'm')) || [])[1]?.trim();
  const hostname = (text.match(/-\s*hostname:\s*(\S+)/) || [])[1] || null;
  const service = (text.match(/service:\s*http:\/\/127\.0\.0\.1:(\d+)/) || [])[1] || null;
  return { tunnel: get('tunnel'), credentialsFile: get('credentials-file'), hostname, port: service ? Number(service) : null, path: p };
}

/**
 * Start a tunnel. Returns {mode, url, child, stop}.
 * mode === 'named' when a hostname is configured, else 'quick'.
 */
export function startTunnel({ port, name = null, hostname = null, configFile = null, onLog = () => {} }) {
  const bin = cloudflaredBin();
  if (!bin) {
    throw new Error('cloudflared not found on PATH — install it with `brew install cloudflared` and re-run');
  }
  const named = !!(name || configFile);
  const args = named
    ? ['tunnel', '--no-autoupdate', ...(configFile ? ['--config', expand(configFile)] : []), 'run', String(name)]
    : ['tunnel', '--no-autoupdate', '--url', `http://127.0.0.1:${port}`];

  const child = spawn(bin, args.filter(Boolean), { stdio: ['ignore', 'pipe', 'pipe'] });
  let url = null;
  const grab = (chunk) => {
    const text = String(chunk);
    onLog(text.trim());
    const quick = text.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/);
    if (quick) url = quick[0];
    if (!url && named && hostname) url = `https://${hostname}`;
  };
  child.stdout.on('data', grab);
  child.stderr.on('data', grab);

  return {
    mode: named ? 'named' : 'quick',
    child,
    get url() {
      return named && hostname ? `https://${hostname}` : url;
    },
    stop() {
      try { child.kill('SIGTERM'); } catch {}
    },
  };
}

export function tunnelStatus(cfg) {
  const t = cfg.tunnel || {};
  const named = readTunnelConfig();
  return {
    installed: !!cloudflaredBin(),
    logged_in: hasCloudflareCert(),
    configured: t.name ? { name: t.name, hostname: t.hostname, configFile: t.configFile || named?.path || null } : null,
    on_disk: named,
    quick_only: !t.name,
    home: os.homedir(),
  };
}

function run(bin, args, { timeout = 30_000 } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    let err = '';
    const timer = setTimeout(() => {
      child.kill('SIGKILL');
      reject(new Error(`cloudflared ${args.join(' ')} timed out`));
    }, timeout);
    child.stdout.on('data', (c) => (out += c));
    child.stderr.on('data', (c) => (err += c));
    child.on('close', (code) => {
      clearTimeout(timer);
      code === 0 ? resolve(out || err) : reject(new Error((err || out || `exit ${code}`).trim().split('\n').slice(-3).join(' | ')));
    });
    child.on('error', (e) => {
      clearTimeout(timer);
      reject(e);
    });
  });
}

/** Create + route a named tunnel. Touches your Cloudflare account, so it is opt-in. */
export async function createNamedTunnel({ hostname, port, name = 'keysmith' }) {
  const bin = cloudflaredBin();
  if (!bin) throw new Error('cloudflared not found on PATH — `brew install cloudflared`');
  if (!hasCloudflareCert()) throw new Error(`no origin certificate at ${certPath()} — run \`cloudflared tunnel login\` first`);
  const existing = await listNamedTunnels();
  let tunnel = (existing.tunnels || []).find((t) => t.name === name);
  if (!tunnel) {
    const out = await run(bin, ['tunnel', 'create', name]);
    const id = (out.match(/Created new tunnel "([^"]+)" with ID ([0-9a-f-]+)/i) || out.match(/with ID ([0-9a-f-]+)/i) || [])[1];
    if (!id) throw new Error(`could not parse tunnel id from: ${out.trim().split('\n').slice(-2).join(' ')}`);
    tunnel = { id, name };
  }
  await run(bin, ['tunnel', 'route', 'dns', tunnel.id, hostname], { timeout: 60_000 });
  const configFile = writeTunnelConfig({
    tunnelName: name,
    tunnelId: tunnel.id,
    hostname,
    port,
    credentialsFile: expand(`~/.cloudflared/${tunnel.id}.json`),
  });
  return { tunnel, hostname, configFile };
}
